version: 2.1
jobs:
  trigger-e2e-tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.28.0-focal
    steps:
      - checkout
      - run:
          name: Kick off new pipeline
          command: |
            curl --location --request POST 'https://circleci.com/api/v2/project/github/coingaming/hi_casino_e2e_tests/pipeline' \
            --header 'Content-Type: application/json' \
            -u "${E2E_TESTS_API_TOKEN}:"
workflows:
  trigger-e2e-tests-workflow:
    jobs:
      - trigger-e2e-tests
