version: 2.1
jobs:
  trigger-e2e-tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.28.0-focal
    steps:
      - checkout
      - run:
          name: Get status new pipeline
          command: |
            apt-get update 
            apt-get install -y jq

            echo "Status E2E_TESTS_API_TOKEN: ${E2E_TESTS_API_TOKEN}"
            STATUS=$(curl -s "https://circleci.com/api/v2/pipeline/2d0bc4e0-ad99-4f39-9c96-b44d1b0646d9/workflow?circle-token=${E2E_TESTS_API_TOKEN}" \
             | jq -r '.items[].status')

            echo "STATUS: ${STATUS}"

workflows:
  trigger-e2e-tests-workflow:
    jobs:
      - trigger-e2e-tests
