version: 2.1
parameters:
 action:
    type: enum
    enum: [build, report]
    default: build
tests-folder:
    type: string
    default: ""
    description: In order to run moore specific test set, please type on of the ->  backoffice | hi-casino | 8io

jobs:
  e2e_tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Kick off new pipeline
          command: |  
            sudo apt-get update && sudo apt-get install -y jq
            GH_USERNAME=TestUser
            echo "$GH_USERNAME"
            PIPELINE_ID=$(curl --location --request POST 'https://circleci.com/api/v2/project/github/coingaming/platform_e2e_tests/pipeline' \
            -d '{ "parameters": { "tests-folder": "backoffice/finance-admin", "author": "TestUser"  } }' \
            --header 'Content-Type: application/json' \
            -u "${E2E_TESTS_API_TOKEN}:" \
            | jq -r '.id')
            echo "Triggered!"
            echo "export PIPELINE=${PIPELINE_ID}" >> $BASH_ENV
      # - run:
      #     name: Get status new pipeline
      #     command: |
      #       sleep 3
      #       STATUS=$(curl -s "https://circleci.com/api/v2/pipeline/${PIPELINE}/workflow?circle-token=${E2E_TESTS_API_TOKEN}" | jq -r '.items[].status')

      #       while [ "${STATUS}" == "running" ]; do
      #         echo still running
      #         sleep 10
      #         STATUS=$(curl -s "https://circleci.com/api/v2/pipeline/${PIPELINE}/workflow?circle-token=${E2E_TESTS_API_TOKEN}" | jq -r '.items[].status')
      #       done

      #       echo "finally done, checking final status: ${STATUS}"
      #       if [[ "${STATUS}" == "success" ]]; then
      #         echo "Proceeding with build, as triggered pipeline was success"
      #         exit 0
      #       else
      #         echo "Stopping build, triggered pipeline was not a success"
      #         exit 1
      #       fi

workflows:
  trigger-e2e-tests-workflow:
    jobs:
      - e2e_tests
